## model
model_name_or_path: Qwen/Qwen3-4B-Thinking-2507
enable_liger_kernel: true

### method
stage: sft
do_train: true
finetuning_type: full

### ddp
ddp_timeout: 180000000
deepspeed: ./train/deepspeed/ds_z3_config.json
flash_attn: fa2

### dataset
dataset: Apsara-Reason-v1-SFT-stage1
template: qwen
cutoff_len: 65536
packing: true
overwrite_cache: true
preprocessing_num_workers: 32
seed: 42

### output
output_dir: stage1_checkpoints
logging_steps: 1
save_strategy: epoch
save_total_limit: 6
overwrite_output_dir: false
save_only_model: false
plot_loss: true
seed: 42

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1.0e-8
max_grad_norm: 1.0
weight_decay: 0.1
num_train_epochs: 6.0
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs: {'min_lr': 1.0e-5}
warmup_ratio: 0.1
bf16: true